CGP_HEADERS = [
    # Warning, do not alter the order!
    "cluster",
    "region",
    "national_community",
    "milestone_passed",
    "start_date",
    "end_date",
    "completed_book_1",
    "completed_book_2",
    "completed_book_3_1",
    "completed_book_3_2",
    "completed_book_3_3",
    "completed_book_4",
    "completed_book_5",
    "completed_book_6",
    "completed_book_7",
    "completed_book_8_1",
    "completed_book_8_2",
    "completed_book_8_3",
    "completed_book_9_1",
    "completed_book_9_2",
    "completed_book_9_3",
    "completed_book_10_1",
    "completed_book_10_2",
    "completed_book_10_3",
    "devotional_count",
    "devotional_attendance",
    "devotional_friends",
    "children_class_count",
    "children_class_attendance",
    "childrenclass_friends",
    "junior_youth_count",
    "junior_youth_attendance",
    "junior_youth_friends",
    "study_circle_count",
    "study_circle_attendance",
    "study_circle_friends",
    "expansion_phase_participants",
    "expansion_phase_childjunioryouth_registered",
    "expansion_phase_youthadults_enrolled",
    "expansion_phase_newlyenrolled_in_institute",
    "bahai_population_children",
    "bahai_population_junioryouth",
    "bahai_population_youth",
    "bahai_population_adultmen",
    "bahai_population_adultwomen",
    "bahai_population_total",
    "home_visit_count",
    "feast_count",
    "feast_attendance",
    "holy_days_count",
    "holy_days_attendance",
]

CLUSTER_NAME = "cluster_name"
GROUPING = "grouping"

GROUPINGS = {
    "Ada": "Oklahoma",
    "Alexandria Area": "Louisiana",
    "Amarillo Area": "Dallas",
    "Andrews-Crane": "Northeast Tarrant",
    "Ardmore": "Oklahoma",
    "Arlington Mid-Cities": "Northeast Tarrant",
    "Austin Area": "Austin",
    "Bartlesville": "Oklahoma",
    "Bastrop County": "Austin",
    "Baton Rouge Area": "Louisiana",
    "Baxter-Stone": "Arkansas",
    "Boone-Searcy": "Arkansas",
    "Brewster": "San Antonio",
    "Bryan-College Station": "Harris",
    "Cleburne-White": "Arkansas",
    "Cleveland-Chicot": "Arkansas",
    "Coastal Bend": "San Antonio",
    "Coastal Plain": "Austin",
    "Coastal Plain": "San Antonio",
    "Corpus Christi Area": "San Antonio",
    "Cross-St. Francis": "Arkansas",
    "Cross-St. Francis": "Louisiana",
    "Dallas City": "Dallas",
    "Dallas-Union": "Arkansas",
    "De Soto-Natchitoches": "Louisiana",
    "Deep East Pine": "Harris",
    "Denton County North": "Metrocrest",
    "Denton County South": "Metrocrest",
    "East Central Texas": "Dallas",
    "East Central Texas": "Harris",
    "East Collin": "Metrocrest",
    "East Dallas County": "Dallas",
    "East Texas": "Dallas",
    "East Texas": "Harris",
    "East Texas Hilly": "Harris",
    "El Paso Area": "San Antonio",
    "El Reno": "Oklahoma",
    "Elk City-Clinton": "Oklahoma",
    "Ellis-Navarro-Kaufman": "Dallas",
    "Enid": "Oklahoma",
    "Evangeline-Acadia": "Louisiana",
    "Far East North Texas": "Dallas",
    "Far East North Texas": "Northeast Tarrant",
    "Far North Texas": "Dallas",
    "Fort Bend-Brazoria": "Harris",
    "Fort Smith Area": "Arkansas",
    "Fort Worth City": "Northeast Tarrant",
    "Greater Williamson County": "Austin",
    "Gulf Coast": "Harris",
    "Harris County Central": "Harris",
    "Harris County East": "Harris",
    "Harris County West": "Harris",
    "Hays County": "Austin",
    "Hempstead-Columbia": "Arkansas",
    "Hill Country Central": "Austin",
    "Hill Country North": "Austin",
    "Hill Country West": "Austin",
    "Hot Springs Area": "Arkansas",
    "Houma Area Area": "Louisiana",
    "Howard-Little River": "Arkansas",
    "Hudspeth-Reeves": "San Antonio",
    "Johnson County": "Harris",
    "Johnson County": "Northeast Tarrant",
    "Jonesboro Area": "Arkansas",
    "Lafayette Area": "Louisiana",
    "Lake Charles Area": "Louisiana",
    "Laredo Border": "San Antonio",
    "Lawton-Altus": "Oklahoma",
    "Liberty-Hardin": "Harris",
    "Little Rock Area": "Arkansas",
    "Logan": "Oklahoma",
    "Lubbock Area": "Dallas",
    "Martin-Crockett": "Northeast Tarrant",
    "McAlester": "Oklahoma",
    "Metrocrest": "Metrocrest",
    "Miami": "Oklahoma",
    "Monroe Area": "Louisiana",
    "Montgomery County": "Harris",
    "Muskogee": "Oklahoma",
    "New Orleans Area": "Louisiana",
    "Newport Area": "Arkansas",
    "Norman": "Oklahoma",
    "North Central": "Harris",
    "North Central": "Northeast Tarrant",
    "North Collin": "Harris",
    "North Shore-Lake Pontchartrain": "Louisiana",
    "Northeast Corner": "Dallas",
    "Northeast Corner": "Harris",
    "Northeast Dallas County": "Dallas",
    "Northeast Tarrant County": "Northeast Tarrant",
    "Northwest Central": "Austin",
    "Northwest Central": "Northeast Tarrant",
    "Oklahoma City": "Oklahoma",
    "Panhandle": "Dallas",
    "Panhandle East": "Dallas",
    "Panhandle NW": "Dallas",
    "Panhandle SW": "Dallas",
    "Pecos": "San Antonio",
    "Pine Bluff Area": "Arkansas",
    "Plano City": "Metrocrest",
    "Polk-Pike": "Arkansas",
    "Port Arthur-Beaumont Area": "Harris",
    "Prairie-Phillips": "Arkansas",
    "Presidio": "San Antonio",
    "Randolph-Greene": "Arkansas",
    "Rio Grande Valley": "San Antonio",
    "River Parishes": "Louisiana",
    "River Valley": "Arkansas",
    "Rockwall County": "Dallas",
    "San Angelo Sphere": "Austin",
    "San Antonio Area": "San Antonio",
    "San Antonio-Houston Corridor": "Austin",
    "Shawnee": "Oklahoma",
    "Shreveport Area": "Louisiana",
    "Southeast Central": "Austin",
    "Southeast Central": "Dallas",
    "Southeast Central": "Harris",
    "Southeast Corner": "Austin",
    "Southeast Corner": "Harris",
    "Southeast Corner": "San Antonio",
    "Southwest Coastal Plain": "San Antonio",
    "Southwest Dallas County": "Northeast Tarrant",
    "Springdale Area": "Arkansas",
    "Stillwater": "Oklahoma",
    "Terrell": "Dallas",
    "Texarkana Area": "Arkansas",
    "Texarkana Area": "Dallas",
    "Texoma Lake": "Metrocrest",
    "Trans Coastal Bend": "San Antonio",
    "Trans Panhandle": "Dallas",
    "Trans Valley": "San Antonio",
    "Trans West Corridor": "Northeast Tarrant",
    "Tulsa": "Oklahoma",
    "Tyler Area": "Dallas",
    "Valverde-Zavala": "San Antonio",
    "Victoria Area": "San Antonio",
    "Waco Area": "Northeast Tarrant",
    "West Carroll-Tensas": "Louisiana",
    "West Collin": "Metrocrest",
    "Wichita Falls Area": "Metrocrest",
    "Winn-Concordia": "Louisiana",
    "Woodward": "Oklahoma"
}
