CGP_HEADERS = [
    # Warning, do not alter the order!
    "cluster",
    "region",
    "national_community",
    "milestone_passed",
    "start_date",
    "end_date",
    "completed_book_1",
    "completed_book_2",
    "completed_book_3_1",
    "completed_book_3_2",
    "completed_book_3_3",
    "completed_book_4",
    "completed_book_5",
    "completed_book_6",
    "completed_book_7",
    "completed_book_8_1",
    "completed_book_8_2",
    "completed_book_8_3",
    "completed_book_9_1",
    "completed_book_9_2",
    "completed_book_9_3",
    "completed_book_10_1",
    "completed_book_10_2",
    "completed_book_10_3",
    "devotional_count",
    "devotional_attendance",
    "devotional_friends",
    "children_class_count",
    "children_class_attendance",
    "childrenclass_friends",
    "junior_youth_count",
    "junior_youth_attendance",
    "junior_youth_friends",
    "study_circle_count",
    "study_circle_attendance",
    "study_circle_friends",
    "expansion_phase_participants",
    "expansion_phase_childjunioryouth_registered",
    "expansion_phase_youthadults_enrolled",
    "expansion_phase_newlyenrolled_in_institute",
    "bahai_population_children",
    "bahai_population_junioryouth",
    "bahai_population_youth",
    "bahai_population_adultmen",
    "bahai_population_adultwomen",
    "bahai_population_total",
    "home_visit_count",
    "feast_count",
    "feast_attendance",
    "holy_days_count",
    "holy_days_attendance",
]

ACTIVITIES_HEADER = [
    "activity_type",
    "name",
    "national_community",
    "region",
    "cluster",
    "locality",
    "focus_neighbourhood",
    "activity_status",
    "start_date",
    "end_date",
    "total_participants",
    "bahai_participants",
    "service_projects",
    "facilitators",
    "grade_1",
    "grade_2",
    "grade_3",
    "grade_4",
    "grade_5",
    "grade_6",
    "jy_breezes_of_confirmation",
    "jy_glimmerings_of_hope",
    "jy_thinking_about_numbers",
    "jy_spirit_of_faith",
    "jy_walking_the_straight_path",
    "jy_learning_about_excellence",
    "jy_observation_and_insight",
    "jy_the_human_temple",
    "jy_power_of_the_holy_spirit",
    "jy_drawing_on_the_power_of_the_word",
    "sc_1_reflections_on_the_life_of_the_spirit",
    "sc_2_arising_to_serve",
    "sc_3_1_teaching_childrens_classes_grade_1",
    "sc_3_2_teaching_childrens_classes_grade_2",
    "sc_3_3_teaching_childrens_classes_grade_3",
#    "sc_3_4_teaching_childrens_classes_grade_4",  # mysteriously missing from the files
    "sc_4_twin_manifestations",
    "sc_5_releasing_the_powers_of_junior_youth",
    "sc_6_teaching_the_cause",
    "sc_7_walking_together_on_a_path_of_service",
    "sc_8_1_the_center_of_the_covenant_and_his_will_and_testament",
    "sc_8_2_the_guardian_of_the_faith",
    "sc_8_3_the_universal_house_of_justice",
    "sc_9_1_the_eternal_covenant",
    "sc_9_2_a_passage_to_maturity",
    "sc_9_3_a_sacred_enterprise",
    "sc_10_1_accompanying_one_another_on_a_path_of_service",
    "sc_10_2_consultation",
    "sc_10_3_dynamics_of_service_on_area_teaching_committee"
]

ANALYZE_PARTICIPATION_COLUMNS = [
    "completed_book_1",
    "completed_book_2",
    "completed_book_3_1",
    "completed_book_3_2",
    "completed_book_3_3",
    "completed_book_4",
    "completed_book_5",
    "completed_book_6",
    "completed_book_7",
    "completed_book_8_1",
    "completed_book_8_2",
    "completed_book_8_3",
    "completed_book_9_1",
    "completed_book_9_2",
    "completed_book_9_3",
    "completed_book_10_1",
    "completed_book_10_2",
    "completed_book_10_3",
    "devotional_count",
    "devotional_attendance",
    "devotional_friends",
    "children_class_count",
    "children_class_attendance",
    "childrenclass_friends",
    "junior_youth_count",
    "junior_youth_attendance",
    "junior_youth_friends",
    "study_circle_count",
    "study_circle_attendance",
    "study_circle_friends",
]

CLUSTER = "cluster"
CLUSTER_NAME = "cluster_name"
GROUPING = "grouping"

GROUPINGS = {
    "Ada": "Oklahoma",
    "Alexandria Area": "Louisiana",
    "Amarillo Area": "Dallas",
    "Andrews-Crane": "Arlington Mid-Cities",
    "Ardmore": "Oklahoma",
    "Arlington Mid-Cities": "Arlington Mid-Cities",
    "Austin Area": "Austin",
    "Bartlesville": "Oklahoma",
    "Bastrop County": "Austin",
    "Baton Rouge Area": "Louisiana",
    "Baxter-Stone": "Arkansas",
    "Boone-Searcy": "Arkansas",
    "Brewster": "San Antonio",
    "Bryan-College Station": "Harris",
    "Cleburne-White": "Arkansas",
    "Cleveland-Chicot": "Arkansas",
    "Coastal Bend": "San Antonio",
    "Coastal Plain": "Austin",
    "Coastal Plain": "San Antonio",
    "Corpus Christi Area": "San Antonio",
    "Cross-St. Francis": "Arkansas",
    "Cross-St. Francis": "Louisiana",
    "Dallas City": "Dallas",
    "Dallas-Union": "Arkansas",
    "De Soto-Natchitoches": "Louisiana",
    "Deep East Pine": "Harris",
    "Denton County North": "Metrocrest",
    "Denton County South": "Metrocrest",
    "East Central Texas": "Dallas",
    "East Central Texas": "Harris",
    "East Collin": "Metrocrest",
    "East Dallas County": "Dallas",
    "East Texas": "Dallas",
    "East Texas Hilly": "Harris",
    "El Paso Area": "San Antonio",
    "El Reno": "Oklahoma",
    "Elk City-Clinton": "Oklahoma",
    "Ellis-Navarro-Kaufman": "Dallas",
    "Enid": "Oklahoma",
    "Evangeline-Acadia": "Louisiana",
    "Far East North Texas": "Dallas",
    "Far North Texas": "Dallas",
    "Fort Bend-Brazoria": "Harris",
    "Fort Smith Area": "Arkansas",
    "Fort Worth City": "Arlington Mid-Cities",
    "Greater Williamson County": "Austin",
    "Gulf Coast": "Harris",
    "Harris County Central": "Harris",
    "Harris County East": "Harris",
    "Harris County West": "Harris",
    "Hays County": "Austin",
    "Hempstead-Columbia": "Arkansas",
    "Hill Country Central": "Austin",
    "Hill Country North": "Austin",
    "Hill Country West": "Austin",
    "Hot Springs Area": "Arkansas",
    "Houma Area Area": "Louisiana",
    "Howard-Little River": "Arkansas",
    "Hudspeth-Reeves": "San Antonio",
    "Johnson County": "Arlington Mid-Cities",
    "Jonesboro Area": "Arkansas",
    "Lafayette Area": "Louisiana",
    "Lake Charles Area": "Louisiana",
    "Laredo Border": "San Antonio",
    "Lawton-Altus": "Oklahoma",
    "Liberty-Hardin": "Harris",
    "Little Rock Area": "Arkansas",
    "Logan": "Oklahoma",
    "Lubbock Area": "Dallas",
    "Martin-Crockett": "Arlington Mid-Cities",
    "McAlester": "Oklahoma",
    "Metrocrest": "Metrocrest",
    "Miami": "Oklahoma",
    "Monroe Area": "Louisiana",
    "Montgomery County": "Harris",
    "Muskogee": "Oklahoma",
    "New Orleans Area": "Louisiana",
    "Newport Area": "Arkansas",
    "Norman": "Oklahoma",
    "North Central": "Arlington Mid-Cities",
    "North Collin": "Harris",
    "North Shore-Lake Pontchartrain": "Louisiana",
    "Northeast Corner": "Dallas",
    "Northeast Dallas County": "Dallas",
    "Northeast Tarrant County": "Arlington Mid-Cities",
    "Northwest Central": "Arlington Mid-Cities",
    "Oklahoma City": "Oklahoma",
    "Panhandle": "Dallas",
    "Panhandle East": "Dallas",
    "Panhandle NW": "Dallas",
    "Panhandle SW": "Dallas",
    "Pecos": "San Antonio",
    "Pine Bluff Area": "Arkansas",
    "Plano City": "Metrocrest",
    "Polk-Pike": "Arkansas",
    "Port Arthur-Beaumont Area": "Harris",
    "Prairie-Phillips": "Arkansas",
    "Presidio": "San Antonio",
    "Randolph-Greene": "Arkansas",
    "Rio Grande Valley": "San Antonio",
    "River Parishes": "Louisiana",
    "River Valley": "Arkansas",
    "Rockwall County": "Dallas",
    "San Angelo Sphere": "Austin",
    "San Antonio Area": "San Antonio",
    "San Antonio-Houston Corridor": "Austin",
    "Shawnee": "Oklahoma",
    "Shreveport Area": "Louisiana",
    "Southeast Central": "Harris",
    "Southeast Corner": "Harris",
    "Southwest Coastal Plain": "San Antonio",
    "Southwest Dallas County": "Arlington Mid-Cities",
    "Springdale Area": "Arkansas",
    "Stillwater": "Oklahoma",
    "Terrell": "Dallas",
    "Texarkana Area": "Dallas",
    "Texoma Lake": "Metrocrest",
    "Trans Coastal Bend": "San Antonio",
    "Trans Panhandle": "Dallas",
    "Trans Valley": "San Antonio",
    "Trans West Corridor": "Arlington Mid-Cities",
    "Tulsa": "Oklahoma",
    "Tyler Area": "Dallas",
    "Valverde-Zavala": "San Antonio",
    "Victoria Area": "San Antonio",
    "Waco Area": "Arlington Mid-Cities",
    "West Carroll-Tensas": "Louisiana",
    "West Collin": "Metrocrest",
    "Wichita Falls Area": "Metrocrest",
    "Winn-Concordia": "Louisiana",
    "Woodward": "Oklahoma"
}
